#!/usr/bin/env bash
#Bash script that moves a file from client to server passed at the command line as arguments

if [ $# -lt 4 ]; then
	echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
	exit 1
fi

path_to_file=$1
ip=$2
username=$3
path_to_ssh_key=$4

#transfer the file to the server
scp -i "$4" -o StrictHostKeyChecking=no "$1" "$3@$2:~/"
