#!/usr/bin/env bash
#Checking for multiples of 5 and 3
i=1
while [ "$i" -lt 101 ]
do
	if (( i % 3 == 0 && i % 5 == 0 ))
	then
		echo "FizzBuzz"
	elif (( i % 3 == 0 ))
	then
		echo "Fizz"
	elif (( i % 5 == 0))
	then
		echo "Buzz"
	else
		echo "$i"
	fi
	((i++))
done
