#!/usr/bin/env bash
#Printing bad luck on the 4th iteration and good luck on the 8th iteration.
i=0
while (("$i" < 10))
do
	if [ "$i" == 3 ]
	then
		echo "bad luck"
	elif [ "$i" == 7 ]
	then
		echo "good luck"
	else
		echo "Best School"
	fi
	((i++))
done 
